#!/bin/bash
trap 'echo "Killing process"; kill 0' EXIT

DIR="$1"

# Path to scripts
OPTIMIZER_SCRIPT="/home/incred/work/imgsoptimizer/imgsoptimizer/jpgpngoptimizer"
CONV2WEBP_SCRIPT="/home/incred/work/imgsoptimizer/imgsoptimizer/conv2webp"
FINDNOPTIMIZE_SCRIPT="/home/incred/work/imgsoptimizer/imgsoptimizer/findimgswithoutattr"

echo "Starting process"
$FINDNOPTIMIZE_SCRIPT $1 &

inotifywait -r -m -q -e create --format %w%f $DIR | while read FILE
do
    $OPTIMIZER_SCRIPT "$FILE" && attr -s optimized -V yes "$FILE"
    nice -n 19 ionice -c 3 $CONV2WEBP_SCRIPT "$FILE"
done
